# Generated by Django 4.2.2 on 2023-06-22 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionListing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=280)),
                ("startingBid", models.PositiveIntegerField()),
                ("imageUrl", models.URLField()),
                ("category", models.CharField(max_length=80)),
                ("isClosed", models.BooleanField(default=False)),
                (
                    "listingUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
