# Generated by Django 4.2.2 on 2023-06-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_rename_bids_bid_rename_comments_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="bidAmount",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
