# Generated by Django 4.2.2 on 2023-06-22 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_bid_bidamount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="listingUserId",
            new_name="listingUserName",
        ),
        migrations.RenameField(
            model_name="bid",
            old_name="bidderUserId",
            new_name="bidderUserName",
        ),
    ]
