# Generated by Django 4.2.2 on 2023-06-22 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "auctions",
            "0006_rename_listinguserid_auctionlisting_listingusername_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="listingUserName",
            new_name="listingUserId",
        ),
        migrations.RenameField(
            model_name="bid",
            old_name="bidderUserName",
            new_name="bidderUserId",
        ),
    ]
