# Generated by Django 4.2.2 on 2023-06-22 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "auctions",
            "0007_rename_listingusername_auctionlisting_listinguserid_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="startingBid",
            new_name="currentPrice",
        ),
    ]
