# Generated by Django 4.2.2 on 2023-06-23 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_rename_listinguserid_auctionlisting_listingusername"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="timeCreated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="imageUrl",
            field=models.URLField(
                default="https://static.vecteezy.com/system/resources/previews/005/720/408/original/crossed-image-icon-picture-not-available-delete-picture-symbol-free-vector.jpg"
            ),
        ),
    ]
