# Generated by Django 4.2.2 on 2023-07-03 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("vidyo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscribe",
            name="subscriber",
        ),
        migrations.RemoveField(
            model_name="subscribe",
            name="subscriptions",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="timePosted",
            new_name="timestamp",
        ),
        migrations.AddField(
            model_name="video",
            name="video",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="static/vidyo/videos"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(upload_to="static/vidyo/thumbnails"),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Subscribe",
        ),
    ]
