# Generated by Django 4.2.2 on 2023-07-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vidyo", "0003_alter_video_thumbnail_alter_video_video_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="commentText",
            field=models.CharField(default="test", max_length=280),
            preserve_default=False,
        ),
    ]
