# Generated by Django 4.2.2 on 2023-07-04 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vidyo", "0005_subscribe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscribe",
            old_name="subscription",
            new_name="subscriptions",
        ),
    ]
