# Generated by Django 4.2.2 on 2023-07-03 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_remove_post_likes_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="Heart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hearts",
                        to="network.post",
                    ),
                ),
                (
                    "user_who_hearted_it",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_who_hearted_it",
                        to="network.post",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
