# Generated by Django 4.2.2 on 2023-07-03 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0005_heart_delete_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heart",
            name="user_who_hearted_it",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_who_hearted_it",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
