# Generated by Django 4.2.2 on 2023-07-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0006_alter_heart_user_who_hearted_it"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hearts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Heart",
        ),
    ]
